---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teku.fullname" . }}-discovery
  labels:
    app.kubernetes.io/name: service-discovery
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
    - name: elc-rlpx
      port: {{ .Values.node.elc.p2p.port }}
      targetPort: elc-rlpx
      protocol: TCP
    - name: elc-discovery
      port: {{ .Values.node.elc.p2p.port }}
      targetPort: elc-discovery
      protocol: UDP
    - name: libp2p
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: libp2p
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: discovery
      protocol: UDP