---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teku.fullname" . }}
  labels:
    app: {{ template "teku.fullname" . }}
    chart: {{ template "teku.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "teku.fullname" . }}
    helm.sh/chart: {{ include "teku.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ template "teku.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "teku.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: elc-rpc
      port: {{ .Values.node.besu.rpc.port }}
      targetPort: elc-rpc
      protocol: TCP
    - name: elc-ws
      port: {{ .Values.node.besu.ws.port }}
      targetPort: elc-ws
      protocol: TCP
    - name: elc-graphql
      port: {{ .Values.node.besu.graphql.port }}
      targetPort: elc-graphql
      protocol: TCP
    - name: elc-rlpx
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: elc-rlpx
      protocol: TCP
    - name: elc-discovery
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: elc-discovery
      protocol: UDP
    - name: elc-metrics
      port: {{ .Values.node.besu.metrics.port }}
      targetPort: elc-metrics
      protocol: TCP
      
    - name: discovery
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: discovery
      protocol: TCP
    - name: rest-api
      port: {{ .Values.node.teku.restApi.port }}
      targetPort: rest-api
      protocol: TCP
    - name: metrics
      port: {{ .Values.node.teku.metrics.port }}
      targetPort: metrics
      protocol: TCP      
    

{{- if .Values.node.metrics.serviceMonitorEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "teku.fullname" . }}-servicemonitor
  labels:
    release: monitoring
    helm.sh/chart: {{ include "teku.chart" . }}
    app: {{ template "teku.fullname" . }}
    chart: {{ template "teku.chart" . }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "teku.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teku.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
    honorLabels: true
  - port: elc-metrics
    interval: 15s
    path: /metrics
    scheme: http
    honorLabels: true
{{- end }}