---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teku.fullname" . }}-internal
  labels:
    app.kubernetes.io/name: internal
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
    - name: elc-rpc
      port: {{ .Values.node.elc.rpc.port }}
      targetPort: elc-rpc
      protocol: TCP
    - name: elc-engine
      port: {{ .Values.node.elc.engine.port }}
      targetPort: elc-engine
      protocol: TCP
    - name: elc-rlpx
      port: {{ .Values.node.elc.p2p.port }}
      targetPort: elc-rlpx
      protocol: TCP
    - name: elc-discovery
      port: {{ .Values.node.elc.p2p.port }}
      targetPort: elc-discovery
      protocol: UDP
    - name: elc-metrics
      port: {{ .Values.node.elc.metrics.port }}
      targetPort: elc-metrics
      protocol: TCP
    - name: clc-libp2p
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: clc-libp2p
      protocol: TCP
    - name: clc-discovery
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: clc-discovery
      protocol: UDP
    - name: clc-rest
      port: {{ .Values.node.teku.restApi.port }}
      targetPort: clc-rest
      protocol: TCP
    - name: clc-metrics
      port: {{ .Values.node.teku.metrics.port }}
      targetPort: clc-metrics
      protocol: TCP
{{- if .Values.node.web3signer.enabled }}
    - name: w3s-http
      port: {{ .Values.node.web3signer.http.port }}
      targetPort: w3s-http
      protocol: TCP
    - name: w3s-metrics
      port: {{ .Values.node.web3signer.metrics.port }}
      targetPort: w3s-metrics
      protocol: TCP
{{- end }}      

{{- if .Values.node.metrics.serviceMonitorEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "teku.fullname" . }}-servicemonitor
  labels:
    release: monitoring
    app.kubernetes.io/name: {{ include "teku.fullname" . }}
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: monitoring
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: internal
      app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
      app.kubernetes.io/namespace: {{ .Release.Namespace }}
  endpoints:
  - port: clc-metrics
    interval: 15s
    path: {{ .Values.node.metrics.clcMetricsPath | quote }}
    scheme: http
    honorLabels: true
  - port: elc-metrics
    interval: 15s
    path: {{ .Values.node.metrics.elcMetricsPath | quote }}
    scheme: http
    honorLabels: true
{{- if .Values.node.web3signer.enabled }}
  - port: w3s-metrics
    interval: 15s
    path: {{ .Values.node.metrics.web3signerMetricsPath | quote }}
    scheme: http
    honorLabels: true    
{{- end }}

{{- end }}