---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teku.fullname" . }}-internal
  labels:
    app.kubernetes.io/name: internal
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
    - name: elc-rpc
      port: {{ .Values.node.elc.rpc.port }}
      targetPort: elc-rpc
      protocol: TCP
    - name: elc-engine
      port: {{ .Values.node.elc.engine.port }}
      targetPort: elc-ws
      protocol: TCP
    - name: elc-rlpx
      port: {{ .Values.node.elc.p2p.port }}
      targetPort: elc-rlpx
      protocol: TCP
    - name: elc-discovery
      port: {{ .Values.node.elc.p2p.port }}
      targetPort: elc-discovery
      protocol: UDP
    - name: elc-metrics
      port: {{ .Values.node.elc.metrics.port }}
      targetPort: elc-metrics
      protocol: TCP
    - name: libp2p
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: libp2p
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.teku.p2p.port }}
      targetPort: discovery
      protocol: UDP
    - name: rest-api
      port: {{ .Values.node.teku.restApi.port }}
      targetPort: rest-api
      protocol: TCP
    - name: metrics
      port: {{ .Values.node.teku.metrics.port }}
      targetPort: metrics
      protocol: TCP

{{- if .Values.node.metrics.serviceMonitorEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "teku.fullname" . }}-servicemonitor
  labels:
    release: monitoring
    app.kubernetes.io/name: {{ include "teku.fullname" . }}
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ template "teku.chart" . }}
    app.kubernetes.io/release: monitoring
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
    app.kubernetes.io/name: {{ include "teku.fullname" . }}
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
    honorLabels: true
  - port: elc-metrics
    interval: 15s
    path: /metrics
    scheme: http
    honorLabels: true
{{- end }}