{{- if .Values.node.teku.validators.validatorKeyPath is defined and .Values.node.teku.validators.validatorKeyPath|length }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teku.fullname" . }}-teku-validator-keys
  labels:
    app.kubernetes.io/name: teku-validator-keys
    app.kubernetes.io/component: teku
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "helm/keys/*").AsSecrets | indent 2 }}
{{ (.Files.Glob "helm/passwords/*").AsSecrets | indent 2 }}

{{- end }}