---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "teku.fullname" . }}-teku
  labels:
{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
    aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end }}
    app.kubernetes.io/name: teku-statefulset
    app.kubernetes.io/component: teku
    app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: teku-statefulset
      app.kubernetes.io/component: teku
      app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
      app.kubernetes.io/namespace: {{ .Release.Namespace }}
      app.kubernetes.io/release: {{ .Release.Name }}
      app.kubernetes.io/managed-by: helm
  serviceName: {{ include "teku.fullname" . }}-service-internal
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ include "teku.fullname" . }}-storage
      resources:
        requests:
          storage: "{{ .Values.cluster.storage.pvcSizeLimit }}"
  template:
    metadata:
      labels:
{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
        aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end }}
        app.kubernetes.io/name: teku-statefulset
        app.kubernetes.io/component: teku
        app.kubernetes.io/part-of: {{ include "teku.fullname" . }}
        app.kubernetes.io/namespace: {{ .Release.Namespace }}
        app.kubernetes.io/release: {{ .Release.Name }}
        app.kubernetes.io/managed-by: helm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.node.teku.metrics.port | quote}}
        prometheus.io/path: "/metrics"
    spec:
{{- if and (eq .Values.cluster.provider "aws") (.Values.cluster.cloudNativeServices) }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}
{{- else }}
      serviceAccountName: {{ include "teku.fullname" . }}-sa
{{- end }}
      initContainers:
      - name: wait-for-service
        image: busybox
        command: ["sh", "-c", "while ! nslookup {{ include "teku.fullname" . }}-discovery; do echo 'service still not up' && sleep 1; done;"]
      - name: set-external-ip
        image: gcr.io/cloud-builders/kubectl:latest
        command: ["/bin/bash"]
        args:
          - -c
          - >-
              sleep 10;
              EXTERNALIP=$(kubectl get services -n {{ .Release.Namespace }} {{ include "teku.fullname" . }}-discovery --output jsonpath='{.status.loadBalancer.ingress[0].ip}');
              echo $EXTERNALIP;
              kubectl get cm {{ include "teku.fullname" . }}-teku-config -o yaml -n {{ .Release.Namespace }} | sed "s/p2p-advertised-ip:.*/p2p-advertised-ip: \"${EXTERNALIP}\"/g" | kubectl replace -n {{ .Release.Namespace }} -f -
{{- if has .Values.cluster.provider .Values.cluster.storage.volumePermissionsFix }}
      # fix for minikube and PVC's only writable as root https://github.com/kubernetes/minikube/issues/1990
      - name: set-volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
          - name: data
            mountPath: /data
        securityContext:
          runAsUser: 0
{{- end}}

      containers:
      - name: {{ .Release.Name }}-teku
        image: {{ .Values.image.teku.repository }}:{{ .Values.image.teku.tag }}
        imagePullPolicy: {{ .Values.image.teku.pullPolicy }}
        resources:
          requests:
            cpu: "{{ .Values.node.teku.resources.cpuRequest }}"
            memory: "{{ .Values.node.teku.resources.memRequest }}"
          limits:
            cpu: "{{ .Values.node.teku.resources.cpuLimit }}"
            memory: "{{ .Values.node.teku.resources.memLimit }}"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
{{- if .Values.node.teku.env_opts }}
          - name: TEKU_OPTS
            value: "{{ .Values.node.teku.env_opts }}"
{{- end }}
        volumeMounts:
          - name: teku-config
            mountPath: /etc/teku
            readOnly: true
          - name: keys
            mountPath: {{ .Values.node.teku.keysPath }}
            readOnly: true
          - name: data
            mountPath: {{ .Values.node.teku.dataPath }}
        ports:
          - name: clc-rest
            containerPort: {{ .Values.node.teku.restApi.port }}
            protocol: TCP
          - name: clc-libp2p
            containerPort: {{ .Values.node.teku.p2p.port }}
            protocol: TCP
          - name: clc-discovery
            containerPort: {{ .Values.node.teku.p2p.port }}
            protocol: UDP
          - name: clc-metrics
            containerPort: {{ .Values.node.teku.metrics.port }}
            protocol: TCP
        command:
          - /bin/sh
          - -c
        args:
          - |
            exec
            /opt/teku/bin/teku \
              -c /etc/teku/config.yml

        livenessProbe:
          httpGet:
            path: /liveness
            port: 8545
          initialDelaySeconds: 180
          periodSeconds: 60
      volumes:
      - name: teku-config
        configMap:
          name: {{ include "teku.fullname" . }}-teku-config
      - name: keys
        secret:
          secretName: {{ include "teku.fullname" . }}-keys