apiVersion: v1
version: 0.0.1
appVersion: 22.7.0
name: teku
description: Teku 
keywords:
  - ethereum
  - teku
  - hyperledger
  - enterprise
  - blockchain
  - consensys
home: https://docs.teku.consensys.net/en/latest/
sources:
  - https://github.com/consensys/teku
maintainers:
  - name: Joshua Fernandes
    email: joshua.fernandes@consensys.net
  - name: Eric Lin
    email: eric.lin@consensys.net
icon: http://besu.hyperledger.org/en/latest/favicon.ico

