---
cluster:
  provider: azure # choose from: aws | azure
  cloudNativeServices: false
  storage:
    sizeLimit: "20Gi"
    pvcSizeLimit: "20Gi"
    # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
    reclaimPolicy: "Delete" # choose from: Delete | Retain
  volumePermissionsFix:
    - azure
  aws:
    serviceAccountName: teku-node-secrets-sa # the aws cli commands uses the name 'quorum-node-secrets-sa' so only change this if you altered the name
    region: ap-southeast-2
  azure:
    identityName: quorum-pod-identity # the script/bootstrap.sh uses the name 'quorum-pod-identity' so only change this if you altered the name
    identityClientId: azure-clientId # the clientId of the user assigned managed identity created in the template
    keyvaultName: azure-keyvault
    tenantId: azure-tenantId # the tenant ID of the key vault
    subscriptionId: azure-subscriptionId # the subscription ID to use - this needs to be set explictly when using multi tenancy

node:
  network: mainnet
  removeKeysOnDelete: true
  metrics:
    serviceMonitorEnabled: true
  elc:
    client: besu
    syncmode: "snap" #besu: FAST/FULL/X_SNAP/X_CHECKPOINT ; #geth: snap/full/light
    identity: "tekuElcNode"
    jwtSharedKey: ""
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "4G"
      memRequest: "1G"
    dataPath: "/data"
    keysPath: "/keys"
    logging: INFO
    engine:
      hostAllowlist: 
        - "*"
      host: "0.0.0.0"
      port: 8551
      jwtSecretPath: "/keys/jwtSharedSecret.hex"
      xMmergeSupport: true
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 30303
      discovery: true
      maxPeers: 25
    rpc:
      enabled: true
      host: "0.0.0.0"
      port: 8545
      api: 
        - debug
        - eth
        - admin
        - web3
        - net
        - trace
        - txpool
      hostAllowlist: 
        - "*"
      vHosts: 
        - "*"
      corsOrigins:
        - "*"
      authenticationEnabled: false
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 9545
    besu:
      envBesuOpts: ""
    geth:
      verbosity: 3
  teku:
    network: mainnet
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "4G"
      memRequest: "1G"
    dataStorageMode: "prune"
    dataPath: "/data"
    keysPath: "/keys"
    logging: INFO
    env_opts: ""
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 9000
      discovery: true
      lowBoundPeers: 64
      upperBoundPeers: 100
    restApi:
      enabled: true
      host: "0.0.0.0"
      port: 5051
      corsOrigins: '["*"]'
      allowlist: '["*"]'
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 8008
      allowlist: '["*"]'
      categories: "['BEACON', 'JVM', 'PROCESS', 'DISCOVERY', 'EVENTBUS', 'EXECUTOR', 'LIBP2P', 'NETWORK', 'STORAGE', 'STORAGE_HOT_DB', 'STORAGE_FINALIZED_DB', 'REMOTE_VALIDATOR', 'VALIDATOR', 'VALIDATOR_PERFORMANCE']"
    metricsPush:
      enabled: false
      host: "5.5.5.5"
      interval: 15
    validators:
      enabled: false
      performanceTrackingMode: "ALL"
      validatorKeysPath: "/validator"
      validatorPasswordsPath: "/validator"
      validatorDefaultFeeRecipient: "0x000095E79eAC4d76aab57cB2c1f091d553b36ca0"

image:
  teku:
    repository: consensys/teku
    tag: 22.9.0
    pullPolicy: IfNotPresent
  besu:
    repository: hyperledger/besu
    tag: 22.7.2
    pullPolicy: IfNotPresent
  geth:
    repository: ethereum/client-go
    tag: v1.10.23-amd64
    pullPolicy: IfNotPresent
  hooks:
    repository: consensys/quorum-k8s-hooks
    tag: qgt-0.2.3
    pullPolicy: IfNotPresent
