---

tekuFlags:
  elClient: besu
  removeKeysOnDelete: true

storage:
  sizeLimit: "20Gi"
  pvcSizeLimit: "20Gi"
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Delete" # choose from: Delete | Retain 

node:
  metrics:
    serviceMonitorEnabled: false
  teku:
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    dataPath: "/data/teku"     
    keysPath: "/keys"
    logging: INFO
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 9000
      discovery: true
      maxPeers: 50
    restApi:
      enabled: true
      host: "0.0.0.0"
      port: 5051
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "NET", "TRACE", "TXPOOL"]'
      corsOrigins: '["all"]'
      allowlist: '["*"]'
      authenticationEnabled: false
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 8008
    metricsPush:
      enabled: false
      host: "5.5.5.5"
      interval: 15

  besu:
    envBesuOpts: ""
    resources:
      cpuLimit: 0.7
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    dataPath: "/data/besu"
    keysPath: "/keys"
    logging: INFO
    engine:
      hostAllowlist: '["*"]'
      rpcPort: 8551
      jwtSecretPath: "/keys/jwtsecret.hex"
      xMmergeSupport: true
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 30303
      discovery: true
      maxPeers: 25
    rpc:
      enabled: true
      host: "0.0.0.0"
      port: 8545
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "NET", "TRACE", "TXPOOL"]'
      corsOrigins: '["all"]'
      authenticationEnabled: false
    ws:
      enabled: false
      host: "0.0.0.0"
      port: 8546
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "NET", "TRACE", "EEA", "TXPOOL"]'
      authenticationEnabled: false
    graphql:
      enabled: false
      host: "0.0.0.0"
      port: 8547
      corsOrigins: '["all"]'
    txPool:
      retentionHours: 999
      maxSize: 1024
    http:
      allowlist: '["*"]'
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 9545
      # enable if using prometheus-stack metrics monitoring
      serviceMonitorEnabled: false      
    metricsPush:
      enabled: false
      host: "5.5.5.5"
      port: 9091
      interval: 15
      # TODO: what is this again? add comments here
      prometheusJob: "besu"
    
    
cluster:
  provider: local  # choose from: local | aws | azure
  cloudNativeServices: false 
  reclaimPolicy: Delete # set to either Retain or Delete; note that PVCs and PVs will still exist after a 'helm delete'. Setting to Retain will keep volumes even if PVCs/PVs are deleted in kubernetes. Setting to Delete will remove volumes from EC2 EBS when PVC is deleted

aws:
  # the aws cli commands uses the name 'quorum-node-secrets-sa' so only change this if you altered the name
  serviceAccountName: teku-node-secrets-sa
  # the region you are deploying to
  region: ap-southeast-2

azure:
  # the script/bootstrap.sh uses the name 'quorum-pod-identity' so only change this if you altered the name
  identityName: quorum-pod-identity
  # the clientId of the user assigned managed identity created in the template
  identityClientId: azure-clientId
  keyvaultName: azure-keyvault
  # the tenant ID of the key vault
  tenantId: azure-tenantId
  # the subscription ID to use - this needs to be set explictly when using multi tenancy
  subscriptionId: azure-subscriptionId

image:
  besu:
    repository: hyperledger/besu
    tag: 22.7.0
    pullPolicy: IfNotPresent
  teku:
    repository: consensys/teku
    tag: 22.7.0
    pullPolicy: IfNotPresent
  hooks:
    repository: consensys/quorum-k8s-hooks
    tag: qgt-0.1.7
    pullPolicy: IfNotPresent
