---
cluster:
  provider: azure # choose from: aws | azure
  cloudNativeServices: false
  storage:
    sizeLimit: "20Gi"
    pvcSizeLimit: "20Gi"
    # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
    reclaimPolicy: "Delete" # choose from: Delete | Retain
  volumePermissionsFix:
    - azure

node:
  network: mainnet
  removeKeysOnDelete: true
  metrics:
    serviceMonitorEnabled: false
  elc:
    client: besu
    resources:
      cpuLimit: 0.7
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    dataPath: "/data"
    keysPath: "/keys"
    logging: INFO
    engine:
      hostAllowlist: '["*"]'
      port: 8551
      jwtSecretPath: "/keys/jwtSharedSecret.hex"
      xMmergeSupport: true
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 30303
      discovery: true
      maxPeers: 25
    rpc:
      enabled: true
      host: "0.0.0.0"
      port: 8545
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "NET", "TRACE", "TXPOOL"]'
      corsOrigins: '["all"]'
      authenticationEnabled: false
    http:
      allowlist: '["*"]'
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 9545
      # enable if using prometheus-stack metrics monitoring
      serviceMonitorEnabled: false
    besu:
      envBesuOpts: ""
    geth:
      verbosity: 3
  teku:
    network: mainnet
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    dataPath: "/data"
    keysPath: "/keys"
    logging: INFO
    p2p:
      enabled: true
      host: "0.0.0.0"
      port: 9000
      discovery: true
      maxPeers: 50
    restApi:
      enabled: true
      host: "0.0.0.0"
      port: 5051
      api: '["DEBUG","ETH", "ADMIN", "WEB3", "NET", "TRACE", "TXPOOL"]'
      corsOrigins: '["all"]'
      allowlist: '["*"]'
      authenticationEnabled: false
    metrics:
      enabled: true
      host: "0.0.0.0"
      port: 8008
    metricsPush:
      enabled: false
      host: "5.5.5.5"
      interval: 15

aws:
  # the aws cli commands uses the name 'quorum-node-secrets-sa' so only change this if you altered the name
  serviceAccountName: teku-node-secrets-sa
  # the region you are deploying to
  region: ap-southeast-2

azure:
  # the script/bootstrap.sh uses the name 'quorum-pod-identity' so only change this if you altered the name
  identityName: quorum-pod-identity
  # the clientId of the user assigned managed identity created in the template
  identityClientId: azure-clientId
  keyvaultName: azure-keyvault
  # the tenant ID of the key vault
  tenantId: azure-tenantId
  # the subscription ID to use - this needs to be set explictly when using multi tenancy
  subscriptionId: azure-subscriptionId

image:
  besu:
    repository: hyperledger/besu
    tag: 22.7.0
    pullPolicy: IfNotPresent
  teku:
    repository: consensys/teku
    tag: 22.7.0
    pullPolicy: IfNotPresent
  hooks:
    repository: consensys/quorum-k8s-hooks
    tag: 22.9.1
    pullPolicy: IfNotPresent
