---
cluster:
  provider: azure # choose from: aws | azure
  cloudNativeServices: false
  storage:
    sizeLimit: "20Gi"
    pvcSizeLimit: "20Gi"
    # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
    reclaimPolicy: "Delete" # choose from: Delete | Retain
  volumePermissionsFix:
    - azure
  aws:
    serviceAccountName: teku-node-secrets-sa # the aws cli commands uses the name 'quorum-node-secrets-sa' so only change this if you altered the name
    region: ap-southeast-2
  azure:
    identityName: quorum-pod-identity # the script/bootstrap.sh uses the name 'quorum-pod-identity' so only change this if you altered the name
    identityClientId: azure-clientId # the clientId of the user assigned managed identity created in the template
    keyvaultName: azure-keyvault
    tenantId: azure-tenantId # the tenant ID of the key vault
    subscriptionId: azure-subscriptionId # the subscription ID to use - this needs to be set explictly when using multi tenancy

node:
  removeKeysOnDelete: true
  metrics:
    serviceMonitorEnabled: true
  teku:
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "8G"
      memRequest: "6G"
    validators:
      enabled: false
      performanceTrackingMode: "ALL"
      validatorKeysPath: "/validator"
      validatorPasswordsPath: "/validator"
      validatorDefaultFeeRecipient: "0x000095E79eAC4d76aab57cB2c1f091d553b36ca0"
    initialState: ""
    env_opts: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Xmx8g -XX:SoftMaxHeapSize=3g"
  elc:
    client: besu
    jwtSharedKey: ""
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "4G"
      memRequest: "2G"
    dataPath: "/data"
  besu:
    envBesuOpts: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data -Xmx4g -XX:SoftMaxHeapSize=2g"
