{
 "title": "Teku - Detailed",
 "description": "An example dashboard showing detailed metrics for multiple Teku instances.",
 "tags": [
  "eth2.0",
  "ethereum",
  "teku"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "validator_local_validator_count{network=~\"$network\",alerting=~\"$alerting\"}"
    }
   },
   { "name": "network", "label": "Network", "query": { "query": "label_values(network)" } },
   { "name": "alerting", "label": "Alerting", "query": { "query": "label_values(alerting)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Difficulty To Mainnet Merge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "58750000000000000000000 - max(besu_blockchain_difficulty_total{network=\"mainnet\"})",
     "legendFormat": "Remaining Difficulty"
    }
   ]
  },
  {
   "title": "Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "description": "Number of local validators",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (status) (validator_local_validator_counts{instance=~\"$system\"}))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Teku Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "sum by (version) (beacon_teku_version{instance=~\"$system\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Published Blocks",
   "type": "stat",
   "description": "Number of blocks published",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"publish_block\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Attestations",
   "type": "stat",
   "description": "Number of attestations published",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"publish_attestation\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Aggregates",
   "type": "stat",
   "description": "Number of aggregates published",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"publish_aggregate_and_proofs\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Published Sync Committee Messages",
   "type": "stat",
   "description": "Number of sync committee messages published.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_requests_total{instance=~\"$system\",method=\"send_sync_committee_messages\",outcome=\"success\"})"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "stat",
   "description": "Total number of active validators in the network.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(beacon_current_active_validators{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Attestation Performance",
   "type": "graph",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg((validator_performance_included_attestations{instance=~\"$system\"} / validator_performance_expected_attestations{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Included"
    },
    {
     "expr": "clamp_max(avg((validator_performance_correct_head_block_count{instance=~\"$system\"} / validator_performance_included_attestations{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Correct Head"
    },
    {
     "expr": "avg((validator_performance_correct_target_count{instance=~\"$system\"} / validator_performance_included_attestations{instance=~\"$system\"}) >= 0)",
     "legendFormat": "{{instance}} Correct Target"
    },
    {
     "expr": "clamp_max(avg(\n((\nvalidator_performance_correct_head_block_count{instance=~\"$system\"} - (validator_performance_expected_attestations{instance=~\"$system\"} - validator_performance_correct_head_block_count{instance=~\"$system\"}) +\nvalidator_performance_correct_target_count{instance=~\"$system\"} - (validator_performance_expected_attestations{instance=~\"$system\"} - validator_performance_correct_target_count{instance=~\"$system\"}) +\nvalidator_performance_included_attestations{instance=~\"$system\"} - (validator_performance_expected_attestations{instance=~\"$system\"} - validator_performance_included_attestations{instance=~\"$system\"}) +\n(0.875  * validator_performance_included_attestations{instance=~\"$system\"} / validator_performance_inclusion_distance_average{instance=~\"$system\"})\n) / validator_performance_expected_attestations{instance=~\"$system\"} / 3.875)>=0), 1)",
     "legendFormat": "{{instance}} Attestation Rewards Earned"
    },
    {
     "expr": "clamp_max(avg((validator_performance_included_sync_committee_messages{instance=~\"$system\"} / validator_performance_expected_sync_committee_messages{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Included Signatures"
    },
    {
     "expr": "clamp_max(avg((validator_performance_produced_sync_committee_messages{instance=~\"$system\"} / validator_performance_expected_sync_committee_messages{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Produced Signatures"
    },
    {
     "expr": "clamp_max(avg((validator_performance_correct_sync_committee_messages{instance=~\"$system\"} / validator_performance_produced_sync_committee_messages{instance=~\"$system\"}) >= 0), 1)",
     "legendFormat": "{{instance}} Correct Signatures"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Distance (slots)",
   "type": "graph",
   "description": "Number of slots between when an attestation is created to when it is included in a block. The minimum possible inclusion distance is 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "validator_performance_inclusion_distance_min{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Minimum"
    },
    {
     "expr": "validator_performance_inclusion_distance_average{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Average"
    },
    {
     "expr": "validator_performance_inclusion_distance_max{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Maximum"
    }
   ]
  },
  {
   "title": "Included Blocks",
   "type": "graph",
   "description": "Percentage of blocks produced in each epoch that were successfully included in the canonical chain.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "validator_performance_included_blocks{instance=~\"$system\"} / validator_performance_expected_blocks{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Included Blocks"
    }
   ]
  },
  {
   "title": "Validator Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Attestation Production Delay",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (interval) (rate(validator_attestation_publication_delay{instance=~\"$system\"}[5m]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Block Production Delay",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (interval) (rate(validator_block_publication_delay{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Attestation Delays",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(validator_attestation_publication_delay{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Block Delays",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(validator_block_publication_delay{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beacon Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_slot{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "description": "Slot of the latest imported block",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_head_slot{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Justified Epoch",
   "type": "stat",
   "description": "Current justified epoch",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_current_justified_epoch{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_finalized_epoch{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Total number of peers connected to the selected nodes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (network) (beacon_peer_count{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_epoch{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "stat",
   "description": "Number of slots the head block is behind.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "max without (alerting, job, instance, client) (beacon_slot{instance=~\"$system\"} - beacon_head_slot{instance=~\"$system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Justification Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that justification has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(min without (instance, job, alerting, client) (beacon_epoch{instance=~\"$system\"} - beacon_current_justified_epoch{instance=~\"$system\"} - 1), 0)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Finalisation Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that finalisation has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(min without (instance, job, alerting, client) (beacon_epoch{instance=~\"$system\"} - beacon_finalized_epoch{instance=~\"$system\"} - 2), 0)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Network Participation Rate",
   "type": "stat",
   "description": "Percentage of validators which voted for the correct target in the previous epoch.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (network) (beacon_previous_correct_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Trailing Distance",
   "type": "graph",
   "description": "Number of slots the head block is behind the current slot. Empty slots may mean the head block trails by a few slots.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "clamp_min(beacon_slot{instance=~\"$system\"} - beacon_head_slot{instance=~\"$system\"}, 0)",
     "legendFormat": "{{instance}} Head Slot"
    },
    {
     "expr": "clamp_min(min(beacon_epoch{instance=~\"$system\"} - beacon_current_justified_epoch{instance=~\"$system\"} - 1) without (instance), 0)",
     "legendFormat": "Justification Delay"
    },
    {
     "expr": "clamp_min(min(beacon_epoch{instance=~\"$system\"} - beacon_finalized_epoch{instance=~\"$system\"} - 2) without (instance), 0)",
     "legendFormat": "Finalisation Delay"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "Overall participation rate in the chain. The Correct Validators must be above 2/3rd for the chain to finalize.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (network) (beacon_previous_live_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
     "legendFormat": "{{network}} Live Validators"
    },
    {
     "expr": "max by (network) (beacon_previous_correct_validators{instance=~\"$system\"} / beacon_previous_active_validators{instance=~\"$system\"})",
     "legendFormat": "{{network}} Correct Validators"
    },
    {
     "expr": "max by (network) (beacon_previous_live_sync_committee{instance=~\"$system\"} / (512 * 32))",
     "legendFormat": "{{network}} Sync Committee Participation"
    }
   ]
  },
  {
   "title": "Peer Client Software",
   "type": "graph",
   "description": "Breakdown of client software run by peers. Note that software cannot always be determined for peers and percentage of peers isn't indicative of number of validators using that software.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_client, client) (libp2p_connected_peers_current{instance=~\"$system\"})",
     "legendFormat": "{{exported_client}}"
    }
   ]
  },
  {
   "title": "Beacon Node Block Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Prepared Proposers",
     "type": "stat",
     "description": "Total number of prepared proposers",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(beacon_proposers_data_total{instance=~\"$system\", type=\"prepared_proposers\"})"
      }
     ]
    },
    {
     "title": "Registered Validators",
     "type": "stat",
     "description": "Total number of registered validators willing to produce blocks using builder infrastructure",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(beacon_proposers_data_total{instance=~\"$system\", type=\"registered_validators\"})"
      }
     ]
    },
    {
     "title": "Execution Payload Source",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (source) (increase(beacon_execution_payload_source{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Execution Payload Fallback Reason",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (fallback_reason) (increase(beacon_execution_payload_source{instance=~\"$system\", source=\"builder_local_el_fallback\", fallback_reason!~\"\"}[$__range]))",
       "legendFormat": "{{fallback_reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Beacon Node Builder API Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 43 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Status API</center>\n</h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 43 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Validator Registration API</center>\n</h2>"
     }
    },
    {
     "type": "timeseries",
     "description": "Builder Status API",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"status\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"status\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"status\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Status API",
     "gridPos": { "h": 9, "w": 9, "x": 3, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"status\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Validator Registration API",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"register_validators\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 65 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Get Header API</center>\n</h2>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 65 },
     "options": {
      "content": "<h2 style=\"color: #eb7b18; font-size: 17px;\">\n<center>Builder Get Payload API</center>\n</h2>"
     }
    },
    {
     "type": "timeseries",
     "description": "Builder Get Header API",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "timeseries",
     "description": "Builder Get Payload API",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "sum by (interval) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\"}[5m]))",
       "legendFormat": "{{interval}}"
      },
      {
       "expr": "sum by (outcome) (rate(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\", outcome=\"error\"}[5m]))",
       "legendFormat": "FAILED"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Header API",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Header API",
     "gridPos": { "h": 9, "w": 9, "x": 3, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_header\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Payload API",
     "gridPos": { "h": 9, "w": 3, "x": 12, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\"}[$__range]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "type": "piechart",
     "description": "Builder Get Payload API",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_builder_requests_total{instance=~\"$system\", method=\"get_payload\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Block Arrival Delays",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_block_import_delay_counter{instance=~\"$system\", stage=\"arrival\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    },
    {
     "title": "Block Total Processing Time",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (interval) (increase(beacon_block_import_delay_counter{instance=~\"$system\", stage=\"total_processing_time\"}[$__range]))",
       "legendFormat": "{{interval}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m]) / ignoring (job) group_left(instance) (count without(cpu, mode) (node_cpu_seconds_total{instance=~\"$system\",mode=\"idle\"}))",
     "legendFormat": "{{instance}} {{job}}"
    },
    {
     "expr": "avg without (instance) (irate(process_cpu_seconds_total{instance=~\"$system\"}[1m]) / ignoring (job) group_left(instance) (count without(cpu, mode) (node_cpu_seconds_total{instance=~\"$system\",mode=\"idle\"})))",
     "legendFormat": "Average {{job}}"
    },
    {
     "expr": "sum by (instance) (avg by (instance,mode) (irate(node_cpu_seconds_total{instance=~\"$system\",mode!=\"idle\"}[1m])))",
     "legendFormat": "{{instance}} Total CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{job}} {{pool}} Used"
    },
    {
     "expr": "sum by (instance) (jvm_memory_pool_bytes_used{instance=~\"$system\"})",
     "legendFormat": "{{instance}} {{job}} {{pool}} Used Total"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{job}} {{pool}} Process Total"
    },
    {
     "expr": " (jvm_memory_pool_bytes_max{instance=~\"$system\"})",
     "legendFormat": "{{instance}} {{job}} {{pool}} Max"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\"}[1m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "{{instance}} Transmit"
      },
      {
       "expr": "sum by (instance) (irate(node_network_receive_bytes_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "{{instance}} Receive"
      }
     ]
    },
    {
     "title": "Gossip Messages",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(libp2p_gossip_messages_total{instance=~\"$system\"}[1m]))",
       "legendFormat": "{{instance}} Total"
      },
      {
       "expr": "irate(libp2p_gossip_messages_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{topic}}"
      }
     ]
    },
    {
     "title": "RPC Blocks Requested",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(etwork_rpc_blocks_by_root_requested_blocks_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blocks By Root"
      },
      {
       "expr": "irate(network_rpc_blocks_by_range_requested_blocks_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} Blocks By Range"
      }
     ]
    },
    {
     "title": "Peer Disconnect Reasons",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (reason) (increase(network_peer_goodbye_total{instance=~\"$system\"}[$__range]))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Peer Chain Validation Attempts",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (increase(network_peer_chain_validation_attempts{instance=~\"$system\",status!=\"started\"}[$__range]))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{instance=~\"$system\",mountpoint=~\"(/data|/)\"} / node_filesystem_size_bytes{instance=~\"$system\"}",
       "legendFormat": "{{instance}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Active Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$system\",device=\"nvme1n1\"}[1m])",
       "legendFormat": "{{instance}} {{device}} IO Time"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$system\"}[1m]) / irate(node_disk_reads_completed_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{device}} Read Latency"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$system\"}[1m]) / irate(node_disk_writes_completed_total{instance=~\"$system\"}[1m])",
       "legendFormat": "{{instance}} {{device}} Write Latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues, Excecutors and Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Signature Verification Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "executor_signature_verifications_queue_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg without (instance) (executor_signature_verifications_queue_size{instance=~\"$system\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max without (instance) (executor_signature_verifications_queue_size{instance=~\"$system\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Signature Verification Batch Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(executor_signature_verifications_task_count{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count{instance=~\"$system\"}[1m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg without (instance) (irate(executor_signature_verifications_task_count{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count{instance=~\"$system\"}[1m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max without (instance) (irate(executor_signature_verifications_task_count{instance=~\"$system\"}[1m]) / irate(executor_signature_verifications_batch_count{instance=~\"$system\"}[1m]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Signature Verification Batch Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "executor_signature_verifications_batch_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{quantile}}"
    },
    {
     "expr": "avg without (instance) (executor_signature_verifications_batch_size{instance=~\"$system\"})",
     "legendFormat": "Average {{quantile}}"
    }
   ]
  },
  {
   "title": "Pending Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_pending_pool_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Pending {{type}}"
    },
    {
     "expr": "beacon_future_items_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Future {{type}}"
    }
   ]
  },
  {
   "title": "Executor Queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "executor_queue_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "In Memory Storage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "storage_memory_states_cache_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} States"
    },
    {
     "expr": "storage_memory_block_count{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Blocks"
    },
    {
     "expr": "storage_memory_checkpoint_states_cache_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Checkpoint States"
    }
   ]
  },
  {
   "title": "Event Channels",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eventbus_event_published_count{instance=~\"$system\"} - ignoring(subscriber) group_right eventbus_event_consumed_count{instance=~\"$system\"}",
     "legendFormat": "{{instance}} {{channel}} {{subscriber}}"
    }
   ]
  },
  {
   "title": "EL Request Queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "beacon_ee_request_queue_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} EE Queue Size"
    },
    {
     "expr": "beacon_eth1_request_queue_size{instance=~\"$system\"}",
     "legendFormat": "{{instance}} Eth1 Queue Size"
    }
   ]
  }
 ]
}